version: '2'
run:
  modules-download-mode: readonly
output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoinits
    - gosec
    - makezero
    - musttag
    - nestif
    - nilerr
    - perfsprint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - unparam
    - whitespace
    - sloglint
  settings:
    cyclop:
      max-complexity: 30
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - golang.org/x/text
            - golang.org/x/crypto
            - golang.org/x/net
            - alfredoramos.mx/csp-reporter
            - github.com/gofiber/fiber/v3
            - github.com/gofiber/contrib/jwt
            - gorm.io/gorm
            - gorm.io/driver/postgres
            - github.com/google/uuid
            - github.com/aws/aws-sdk-go-v2
            - github.com/valkey-io/valkey-go
            - github.com/go-jose/go-jose/v4
            - github.com/casbin/casbin/v2
            - github.com/ccojocar/zxcvbn-go
            - github.com/xuri/excelize/v2
            - github.com/hibiken/asynq
            - github.com/wneessen/go-mail
            # - github.com/getsentry/sentry-go
            - github.com/goccy/go-yaml
            - github.com/nicksnyder/go-i18n/v2/i18n
            - github.com/BurntSushi/toml
            - github.com/swaggo/swag/v2
            - github.com/zeebo/xxh3
    errchkjson:
      check-error-free-encoding: false
      report-no-exported: true
    forbidigo:
      forbid:
        - pattern: ^(fmt\.Print(|f|ln)|print|println)$
          msg: Do not commit print statements
      analyze-types: true
    gosec:
      severity: medium
      confidence: medium
    govet:
      disable:
        - fieldalignment
        - nilness
      enable-all: true
    nestif:
      min-complexity: 8
    perfsprint:
      err-error: true
      strconcat: false
    prealloc:
      for-loops: true
    unparam:
      check-exported: true
    unused:
      field-writes-are-uses: false
      exported-fields-are-used: false
      parameters-are-used: false
      local-variables-are-used: false
      generated-is-used: false
    whitespace:
      multi-if: true
      multi-func: true
    sloglint:
      attr-only: true
      static-msg: true
      msg-style: capitalized
      key-naming-case: kebab
      args-on-sep-lines: true
      forbidden-keys:
        - time
        - level
        - msg
        - source
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - docs/docs.go
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
