components:
  schemas:
    helpers.CspReport:
      properties:
        csp-report:
          $ref: '#/components/schemas/helpers.cspReportFields'
      type: object
    helpers.cspReportFields:
      properties:
        blocked-uri:
          type: string
        column-number:
          type: integer
        disposition:
          type: string
        document-uri:
          type: string
        effective-directive:
          type: string
        line-number:
          type: integer
        original-policy:
          type: string
        referrer:
          type: string
        script-sample:
          type: string
        source-file:
          type: string
        status-code:
          type: integer
        violated-directive:
          type: string
      type: object
  securitySchemes:
    '@securityDefinitions.bearerauth':
      scheme: bearer
      type: http
externalDocs:
  description: ""
  url: ""
info:
  contact:
    email: alfredoramos@duck.com
    name: Alfredo Ramos
    url: https://alfredoramos.mx
  description: RESTful API backend for CSP Reporter
  license:
    name: AGPL-3.0-or-later
    url: https://spdx.org/licenses/AGPL-3.0-or-later.html
  title: CSP Reporter API
  version: '[[API_VERSION]]'
openapi: 3.1.0
paths:
  /activations/review/{id}:
    patch:
      operationId: api.activations.review
      parameters:
      - description: User UUID
        in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
          text/plain:
            schema:
              oneOf:
              - title: approved
                type: boolean
              - example: "{\r\n\t\"reason\": \"Duplicated account\"\r\n}"
                title: reason
                type: string
        description: Approved status | Rejection reason
      responses:
        "204":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: No Content
      security:
      - bearerauth: []
      summary: Review user activation
      tags:
      - User activation
  /activations/users/all:
    get:
      operationId: api.activations.users.index
      responses:
        "204":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: No Content
      security:
      - bearerauth: []
      summary: List all inactive users pending activation
      tags:
      - User activation
  /auth/check:
    post:
      operationId: api.auth.check
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "204":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: No Content
      security:
      - bearerauth: []
      summary: Check if user is valid
      tags:
      - Auth
  /auth/login:
    post:
      operationId: api.auth.login
      requestBody:
        content:
          application/json:
            schema:
              type: object
          text/plain:
            schema:
              oneOf:
              - example: "{\r\n\t\"email\": \"name@server.tld\"\r\n}"
                title: email
                type: string
              - example: "{\r\n\t\"password\": \"4sUp3rS3cUr3P4$$w0rD\"\r\n}"
                title: password
                type: string
        description: Email | Password
        required: true
      responses:
        "204":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: No Content
      summary: User login
      tags:
      - Auth
  /auth/logout:
    post:
      operationId: api.auth.logout
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "204":
          description: No Content
      security:
      - bearerauth: []
      summary: User logout
      tags:
      - Auth
  /auth/recover:
    post:
      operationId: api.auth.recover
      requestBody:
        content:
          application/json:
            schema:
              type: object
          text/plain:
            schema:
              example: "{\r\n\t\"email\": \"name@server.tld\"\r\n}"
              title: email
              type: string
        description: User email
        required: true
      responses:
        "204":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: No Content
      summary: Send password recovery email
      tags:
      - Auth
  /auth/recover/update:
    patch:
      operationId: api.auth.recover.update
      requestBody:
        content:
          application/json:
            schema:
              type: object
          text/plain:
            schema:
              oneOf:
              - example: "{\r\n\t\"hash\": \"xp7GESkD3Dzbm4Pb3Mtn8xc453KHJeXQvdN\"\r\n}"
                title: hash
                type: string
              - example: "{\r\n\t\"password\": \"4sUp3rS3cUr3P4$$w0rD\"\r\n}"
                title: password
                type: string
              - example: "{\r\n\t\"confirm_password\": \"4sUp3rS3cUr3P4$$w0rD\"\r\n}"
                title: confirm_password
                type: string
        description: Recovery hash | Password | Password confirmation
        required: true
      responses:
        "204":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: No Content
      summary: Update user password
      tags:
      - Auth
  /auth/recover/validate:
    post:
      operationId: api.auth.recover.validate
      requestBody:
        content:
          application/json:
            schema:
              type: object
          text/plain:
            schema:
              example: "{\r\n\t\"hash\": \"xp7GESkD3Dzbm4Pb3Mtn8xc453KHJeXQvdN\"\r\n}"
              title: hash
              type: string
        description: Recovery hash
        required: true
      responses:
        "204":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: No Content
      summary: Validate password recovery token
      tags:
      - Auth
  /auth/refresh:
    patch:
      operationId: api.auth.refresh
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "204":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: No Content
      security:
      - bearerauth: []
      summary: Generate a new access token with a refresh token
      tags:
      - Auth
  /auth/register:
    post:
      operationId: api.auth.register
      requestBody:
        content:
          application/json:
            schema:
              type: object
          text/plain:
            schema:
              oneOf:
              - example: "{\r\n\t\"first_name\": \"John\"\r\n}"
                title: first_name
                type: string
              - example: "{\r\n\t\"last_name\": \"Doe\"\r\n}"
                title: last_name
                type: string
              - example: "{\r\n\t\"email\": \"name@server.tld\"\r\n}"
                title: email
                type: string
              - example: "{\r\n\t\"password\": \"4sUp3rS3cUr3P4$$w0rD\"\r\n}"
                title: password
                type: string
              - example: "{\r\n\t\"confirm_password\": \"4sUp3rS3cUr3P4$$w0rD\"\r\n}"
                title: confirm_password
                type: string
        description: First name | Last name | Email | Password | Password confirmation
        required: true
      responses:
        "204":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: No Content
      summary: User registration
      tags:
      - Auth
  /reports/add:
    post:
      operationId: api.csp.reports.add
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - type: object
              - $ref: '#/components/schemas/helpers.CspReport'
                description: CSP Report
                summary: csp-report
        description: CSP Report
        required: true
      responses:
        "204":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: No Content
      security:
      - bearerauth: []
      summary: Add a new CSP report
      tags:
      - Reports
  /reports/all:
    get:
      operationId: api.csp.reports.index
      responses:
        "204":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: No Content
      security:
      - bearerauth: []
      summary: List all CSP reports
      tags:
      - Reports
  /reports/get/{id}:
    get:
      operationId: api.csp.reports.get
      parameters:
      - description: Report UUID
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "204":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: No Content
      security:
      - bearerauth: []
      summary: Get specific CSP report
      tags:
      - Reports
  /sites/add:
    post:
      operationId: api.sites.add
      requestBody:
        content:
          application/json:
            schema:
              type: object
          text/plain:
            schema:
              oneOf:
              - example: "{\r\n\t\"title\": \"Example Website\"\r\n}"
                title: title
                type: string
              - example: "{\r\n\t\"domain\": \"server.tld\"\r\n}"
                title: domain
                type: string
        description: Title | Domain
        required: true
      responses:
        "204":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: No Content
      security:
      - bearerauth: []
      summary: Add a new allowed site
      tags:
      - Sites
  /sites/all:
    get:
      operationId: api.sites.index
      responses:
        "204":
          content:
            application/json:
              schema:
                additionalProperties:
                  type: string
                type: object
          description: No Content
      security:
      - bearerauth: []
      summary: List all allowed sites
      tags:
      - Sites
  /system/cache/purge:
    post:
      operationId: api.system.cache.purge
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "204":
          description: No Content
      security:
      - bearerauth: []
      summary: Purge cache
      tags:
      - System
  /system/csrf:
    get:
      operationId: api.system.csrf
      responses:
        "204":
          description: No Content
      summary: Generate CSRF cookie
      tags:
      - System
servers:
- description: Development
  url: http://localhost:3000/api/v1
