name: CI

on:
  push:
    branches: [master, dev]
  pull_request: {}

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.1'

      - name: Install dependencies
        run: go mod tidy

      - name: Build app
        run: go build -o ./tmp/csp-reporter .

  security:
    if: ${{ !contains(github.event.head_commit.message, 'skip security') }}
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.1'

      - name: Install dependencies
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Check source
        run: govulncheck -show=traces ./...

      - name: Build app
        run: go build -o ./tmp/csp-reporter .

      - name: Check binary
        run: govulncheck -mode=binary -show=traces ./tmp/csp-reporter

      - name: Security scanner
        # Fix Go version detection
        env:
          GOTOOLCHAIN: auto
        uses: securego/gosec@master
        with:
          args: ./...

  lint:
    if: ${{ !contains(github.event.head_commit.message, 'skip lint') }}
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.1'

      - name: Install dependencies
        run: go install golang.org/x/tools/cmd/deadcode@latest

      - name: Lint with vet
        run: go vet .

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Lint with deadcode
        run: deadcode -test ./...
